name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to App Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Trigger App Runner Deployment
        run: |
          aws apprunner start-deployment --service-arn arn:aws:apprunner:us-east-1:149914652348:service/APP-RUNNER-SERVICE-PANDU/ed718127271a48deb44ae67d2dbe86d2

